cmake_minimum_required(VERSION 4.2)
project(Programacao_Competitiva)

set(CMAKE_CXX_STANDARD 14)

add_executable(Programacao_Competitiva main.cpp
        "Solucoes/Codeforces/Implementacao/104A - Blackjack.cpp"
        "Solucoes/Codeforces/Implementacao/133A - HQ9+.cpp"
        Solucoes/Codeforces/Implementacao/155A.cpp
        "Solucoes/Codeforces/Implementacao/129A - Cookies.cpp"
        "Solucoes/Codeforces/Implementacao/334A - Candy Bags.cpp"
        "Solucoes/Codeforces/Implementacao/200B - Drinks.cpp")
