cmake_minimum_required(VERSION 4.2)
project(Programacao_Competitiva)

set(CMAKE_CXX_STANDARD 14)

add_executable(Programacao_Competitiva main.cpp
        "Solucoes/Codeforces/Implementacao/118B - Present from Lena.cpp"
        "Solucoes/Codeforces/Implementacao/352A - Jeff and Digits.cpp"
        "Solucoes/Codeforces/Implementacao/285A - Slightly Decreasing Permutations.cpp")
